"""employee password MFA server sessions

Revision ID: 1c5baa831ec9
Revises: 2aea407269aa
Create Date: 2026-09-19 21:43:43.102893
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "1c5baa831ec9"
down_revision: str | None = "2aea407269aa"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "auth_rate_limits",
        sa.Column("slot", sa.Integer(), nullable=False),
        sa.Column("attempts", sa.Integer(), nullable=False),
        sa.Column("window_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("locked_until", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("slot", name=op.f("pk_auth_rate_limits")),
    )
    op.create_table(
        "employee_credentials",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("login_name", sa.String(length=100), nullable=False),
        sa.Column("password_hash", sa.String(length=255), nullable=False),
        sa.Column("password_changed_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("password_change_required", sa.Boolean(), nullable=False),
        sa.Column("temporary_expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("temporary_used_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("mfa_enabled", sa.Boolean(), nullable=False),
        sa.Column("encrypted_totp_secret", sa.String(length=500), nullable=True),
        sa.Column("last_totp_step", sa.Integer(), nullable=True),
        sa.Column("revoked_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_employee_credentials_user_id_users")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_employee_credentials")),
        sa.UniqueConstraint("login_name", name=op.f("uq_employee_credentials_login_name")),
        sa.UniqueConstraint("user_id", name=op.f("uq_employee_credentials_user_id")),
    )
    op.create_table(
        "auth_challenges",
        sa.Column("token_hash", sa.String(length=64), nullable=False),
        sa.Column("credential_id", sa.Uuid(), nullable=True),
        sa.Column("stage", sa.String(length=30), nullable=False),
        sa.Column("encrypted_totp_secret", sa.String(length=500), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("consumed_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["credential_id"],
            ["employee_credentials.id"],
            name=op.f("fk_auth_challenges_credential_id_employee_credentials"),
        ),
        sa.PrimaryKeyConstraint("token_hash", name=op.f("pk_auth_challenges")),
    )
    op.create_index(
        op.f("ix_auth_challenges_credential_id"), "auth_challenges", ["credential_id"], unique=False
    )
    op.create_index(
        op.f("ix_auth_challenges_expires_at"), "auth_challenges", ["expires_at"], unique=False
    )
    op.create_table(
        "employee_recovery_codes",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("credential_id", sa.Uuid(), nullable=False),
        sa.Column("code_hash", sa.String(length=64), nullable=False),
        sa.Column("used_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["credential_id"],
            ["employee_credentials.id"],
            name=op.f("fk_employee_recovery_codes_credential_id_employee_credentials"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_employee_recovery_codes")),
        sa.UniqueConstraint("code_hash", name=op.f("uq_employee_recovery_codes_code_hash")),
    )
    op.create_index(
        op.f("ix_employee_recovery_codes_credential_id"),
        "employee_recovery_codes",
        ["credential_id"],
        unique=False,
    )
    op.add_column(
        "app_sessions", sa.Column("last_seen_at", sa.DateTime(timezone=True), nullable=True)
    )
    op.add_column(
        "app_sessions", sa.Column("idle_expires_at", sa.DateTime(timezone=True), nullable=True)
    )
    op.add_column(
        "app_sessions", sa.Column("revoked_at", sa.DateTime(timezone=True), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    connection = op.get_bind()
    if connection.scalar(
        sa.text(
            "SELECT EXISTS (SELECT 1 FROM employee_credentials) OR "
            "EXISTS (SELECT 1 FROM app_sessions WHERE source='employee_password_mfa') OR "
            "EXISTS (SELECT 1 FROM inbox_receipts WHERE event_type LIKE 'employee_auth.%')"
        )
    ):
        raise RuntimeError(
            "Restore a pre-auth backup separately; credential/audit history retained"
        )
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("app_sessions", "revoked_at")
    op.drop_column("app_sessions", "idle_expires_at")
    op.drop_column("app_sessions", "last_seen_at")
    op.drop_index(
        op.f("ix_employee_recovery_codes_credential_id"), table_name="employee_recovery_codes"
    )
    op.drop_table("employee_recovery_codes")
    op.drop_index(op.f("ix_auth_challenges_expires_at"), table_name="auth_challenges")
    op.drop_index(op.f("ix_auth_challenges_credential_id"), table_name="auth_challenges")
    op.drop_table("auth_challenges")
    op.drop_table("employee_credentials")
    op.drop_table("auth_rate_limits")
    # ### end Alembic commands ###
