"""verified MAX chat connections

Revision ID: 20260918_0003
Revises: 20260918_0002
Create Date: 2026-09-18 12:21:09.475410
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "20260918_0003"
down_revision: str | None = "20260918_0002"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "max_chats",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("max_chat_id", sa.String(length=200), nullable=False),
        sa.Column("type", sa.String(length=30), nullable=False),
        sa.Column("title", sa.String(length=500), nullable=True),
        sa.Column("is_channel", sa.Boolean(), nullable=True),
        sa.Column("owner_max_user_id", sa.String(length=200), nullable=True),
        sa.Column("bot_present", sa.Boolean(), server_default="false", nullable=False),
        sa.Column("last_seen_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("lifecycle_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("binding_version", sa.Integer(), server_default="0", nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_max_chats")),
        sa.UniqueConstraint("max_chat_id", name=op.f("uq_max_chats_max_chat_id")),
    )
    op.create_table(
        "chat_connection_requests",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("management_id", sa.Uuid(), nullable=False),
        sa.Column("house_id", sa.Uuid(), nullable=False),
        sa.Column("initiated_by_user_id", sa.Uuid(), nullable=False),
        sa.Column("connector_max_user_id", sa.String(length=200), nullable=True),
        sa.Column("token_hash", sa.String(length=64), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("status", sa.String(length=30), server_default="created", nullable=False),
        sa.Column("candidate_max_chat_id", sa.String(length=200), nullable=True),
        sa.Column("scope_type", sa.String(length=30), nullable=False),
        sa.Column("scope_value", sa.String(length=50), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("claimed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("verified_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("cancelled_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("rejected_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_error_code", sa.String(length=100), nullable=True),
        sa.CheckConstraint(
            "(scope_type = 'house' AND scope_value IS NULL) OR "
            "(scope_type = 'entrance' AND scope_value IS NOT NULL "
            "AND length(trim(scope_value)) > 0)",
            name=op.f("ck_chat_connection_requests_scope"),
        ),
        sa.CheckConstraint(
            "status IN ('created','connector_claimed','chat_detected','max_verified',"
            "'awaiting_approval','completed','expired','cancelled','rejected')",
            name=op.f("ck_chat_connection_requests_status"),
        ),
        sa.ForeignKeyConstraint(
            ["candidate_max_chat_id"],
            ["max_chats.max_chat_id"],
            name=op.f("fk_chat_connection_requests_candidate_max_chat_id_max_chats"),
        ),
        sa.ForeignKeyConstraint(
            ["house_id"],
            ["houses.id"],
            name=op.f("fk_chat_connection_requests_house_id_houses"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["initiated_by_user_id"],
            ["users.id"],
            name=op.f("fk_chat_connection_requests_initiated_by_user_id_users"),
        ),
        sa.ForeignKeyConstraint(
            ["management_id", "house_id"],
            ["house_managements.id", "house_managements.house_id"],
            name="fk_connection_management_house",
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_chat_connection_requests")),
        sa.UniqueConstraint("token_hash", name=op.f("uq_chat_connection_requests_token_hash")),
    )
    op.create_index(
        op.f("ix_chat_connection_requests_management_id"),
        "chat_connection_requests",
        ["management_id"],
        unique=False,
    )
    op.create_index(
        "ix_connection_connector_status",
        "chat_connection_requests",
        ["connector_max_user_id", "status"],
        unique=False,
    )
    op.create_table(
        "chat_bindings",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("max_chat_id", sa.String(length=200), nullable=False),
        sa.Column("connection_request_id", sa.Uuid(), nullable=False),
        sa.Column("house_id", sa.Uuid(), nullable=False),
        sa.Column("management_id", sa.Uuid(), nullable=False),
        sa.Column("scope_type", sa.String(length=30), nullable=False),
        sa.Column("scope_value", sa.String(length=50), nullable=True),
        sa.Column("status", sa.String(length=30), server_default="pending", nullable=False),
        sa.Column("verified_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("verified_by_user_id", sa.Uuid(), nullable=True),
        sa.Column("binding_version", sa.Integer(), nullable=False),
        sa.Column("activated_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("suspended_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("revoked_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("suspension_reason", sa.String(length=100), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "(scope_type = 'house' AND scope_value IS NULL) OR "
            "(scope_type = 'entrance' AND scope_value IS NOT NULL "
            "AND length(trim(scope_value)) > 0)",
            name=op.f("ck_chat_bindings_scope"),
        ),
        sa.CheckConstraint(
            "status IN ('pending','active','suspended','revoked')",
            name=op.f("ck_chat_bindings_status"),
        ),
        sa.CheckConstraint("binding_version > 0", name=op.f("ck_chat_bindings_version")),
        sa.ForeignKeyConstraint(
            ["connection_request_id"],
            ["chat_connection_requests.id"],
            name=op.f("fk_chat_bindings_connection_request_id_chat_connection_requests"),
        ),
        sa.ForeignKeyConstraint(
            ["house_id"],
            ["houses.id"],
            name=op.f("fk_chat_bindings_house_id_houses"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["management_id", "house_id"],
            ["house_managements.id", "house_managements.house_id"],
            name="fk_binding_management_house",
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["max_chat_id"],
            ["max_chats.max_chat_id"],
            name=op.f("fk_chat_bindings_max_chat_id_max_chats"),
        ),
        sa.ForeignKeyConstraint(
            ["verified_by_user_id"],
            ["users.id"],
            name=op.f("fk_chat_bindings_verified_by_user_id_users"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_chat_bindings")),
        sa.UniqueConstraint(
            "connection_request_id", name=op.f("uq_chat_bindings_connection_request_id")
        ),
        sa.UniqueConstraint("max_chat_id", "binding_version", name="uq_chat_binding_version"),
    )
    op.create_index(
        op.f("ix_chat_bindings_management_id"), "chat_bindings", ["management_id"], unique=False
    )
    op.create_index(
        op.f("ix_chat_bindings_max_chat_id"), "chat_bindings", ["max_chat_id"], unique=False
    )
    op.create_index(
        "uq_chat_binding_active",
        "chat_bindings",
        ["max_chat_id"],
        unique=True,
        postgresql_where=sa.text("status = 'active'"),
    )
    op.execute("""
        CREATE FUNCTION protect_chat_binding_scope() RETURNS trigger AS $$
        BEGIN
            IF (NEW.max_chat_id, NEW.house_id, NEW.management_id, NEW.binding_version,
                NEW.connection_request_id, NEW.scope_type, NEW.scope_value)
               IS DISTINCT FROM
               (OLD.max_chat_id, OLD.house_id, OLD.management_id, OLD.binding_version,
                OLD.connection_request_id, OLD.scope_type, OLD.scope_value) THEN
                RAISE EXCEPTION 'binding scope is immutable; use a new connection';
            END IF;
            RETURN NEW;
        END; $$ LANGUAGE plpgsql;
    """)
    op.execute("""
        CREATE TRIGGER chat_binding_scope_immutable BEFORE UPDATE ON chat_bindings
        FOR EACH ROW EXECUTE FUNCTION protect_chat_binding_scope();
    """)
    op.execute("""
        CREATE FUNCTION suspend_management_chat_bindings() RETURNS trigger AS $$
        BEGIN
            IF NEW.status <> 'active' OR
               (NEW.valid_to IS NOT NULL AND NEW.valid_to <= clock_timestamp()) THEN
                UPDATE chat_bindings SET status='suspended', suspended_at=clock_timestamp(),
                    updated_at=clock_timestamp(), suspension_reason='MANAGEMENT_ENDED'
                WHERE management_id=NEW.id AND status='active';
            END IF;
            RETURN NEW;
        END; $$ LANGUAGE plpgsql;
    """)
    op.execute("""
        CREATE TRIGGER management_chat_bindings_ended
        AFTER UPDATE OF status, valid_to ON house_managements
        FOR EACH ROW EXECUTE FUNCTION suspend_management_chat_bindings();
    """)


def downgrade() -> None:
    # A-15 policy: rollback may not discard connection/security history.
    op.execute("""
        DO $$ BEGIN
            IF EXISTS (SELECT 1 FROM max_chats) OR
               EXISTS (SELECT 1 FROM chat_connection_requests) OR
               EXISTS (SELECT 1 FROM jobs WHERE kind LIKE 'max.%') THEN
                RAISE EXCEPTION 'A-07 contains history; restore a pre-A07 backup to roll back';
            END IF;
        END $$;
    """)
    op.execute("DROP TRIGGER management_chat_bindings_ended ON house_managements")
    op.execute("DROP FUNCTION suspend_management_chat_bindings()")
    op.execute("DROP TRIGGER chat_binding_scope_immutable ON chat_bindings")
    op.execute("DROP FUNCTION protect_chat_binding_scope()")
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "uq_chat_binding_active",
        table_name="chat_bindings",
        postgresql_where=sa.text("status = 'active'"),
    )
    op.drop_index(op.f("ix_chat_bindings_max_chat_id"), table_name="chat_bindings")
    op.drop_index(op.f("ix_chat_bindings_management_id"), table_name="chat_bindings")
    op.drop_table("chat_bindings")
    op.drop_index("ix_connection_connector_status", table_name="chat_connection_requests")
    op.drop_index(
        op.f("ix_chat_connection_requests_management_id"), table_name="chat_connection_requests"
    )
    op.drop_table("chat_connection_requests")
    op.drop_table("max_chats")
    # ### end Alembic commands ###
