"""personal MAX notification delivery

Revision ID: 2aea407269aa
Revises: 20260918_0004
Create Date: 2026-09-18 19:27:53.642996
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "2aea407269aa"
down_revision: str | None = "20260918_0004"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "max_destination_limits",
        sa.Column("destination", sa.String(length=200), nullable=False),
        sa.Column("next_allowed_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("lease_token", sa.Uuid(), nullable=True),
        sa.Column("lease_until", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("destination", name=op.f("pk_max_destination_limits")),
    )
    op.create_table(
        "notification_deliveries",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("outbox_message_id", sa.Uuid(), nullable=False),
        sa.Column("recipient_user_id", sa.Uuid(), nullable=False),
        sa.Column("channel", sa.String(length=20), nullable=False),
        sa.Column("purpose", sa.String(length=40), nullable=False),
        sa.Column("ticket_id", sa.Uuid(), nullable=False),
        sa.Column("work_attempt_id", sa.Uuid(), nullable=True),
        sa.Column("launch_ref", sa.String(length=64), nullable=False),
        sa.Column("destination", sa.String(length=200), nullable=True),
        sa.Column("status", sa.String(length=30), nullable=False),
        sa.Column("provider_message_id", sa.String(length=200), nullable=True),
        sa.Column("attempt_count", sa.Integer(), nullable=False),
        sa.Column("retry_count", sa.Integer(), nullable=False),
        sa.Column("next_attempt_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("accepted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("superseded_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_error_code", sa.String(length=100), nullable=True),
        sa.Column("last_error_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("desired_version", sa.Integer(), nullable=False),
        sa.Column("applied_version", sa.Integer(), nullable=False),
        sa.Column("lease_token", sa.Uuid(), nullable=True),
        sa.Column("lease_until", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("channel = 'max'", name=op.f("ck_notification_deliveries_channel")),
        sa.CheckConstraint(
            "purpose IN ('ticket_accepted','work_verification')",
            name=op.f("ck_notification_deliveries_purpose"),
        ),
        sa.CheckConstraint(
            "status IN ('pending','processing','accepted','retry_wait','unknown',"
            "'failed','superseded','skipped')",
            name=op.f("ck_notification_deliveries_status"),
        ),
        sa.CheckConstraint(
            "accepted_at IS NULL OR provider_message_id IS NOT NULL",
            name=op.f("ck_notification_deliveries_accepted"),
        ),
        sa.ForeignKeyConstraint(
            ["outbox_message_id"],
            ["outbox_messages.id"],
            name=op.f("fk_notification_deliveries_outbox_message_id_outbox_messages"),
        ),
        sa.ForeignKeyConstraint(
            ["recipient_user_id"],
            ["users.id"],
            name=op.f("fk_notification_deliveries_recipient_user_id_users"),
        ),
        sa.ForeignKeyConstraint(
            ["ticket_id"], ["tickets.id"], name=op.f("fk_notification_deliveries_ticket_id_tickets")
        ),
        sa.ForeignKeyConstraint(
            ["work_attempt_id"],
            ["work_attempts.id"],
            name=op.f("fk_notification_deliveries_work_attempt_id_work_attempts"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_notification_deliveries")),
        sa.UniqueConstraint("launch_ref", name=op.f("uq_notification_deliveries_launch_ref")),
        sa.UniqueConstraint(
            "outbox_message_id", "recipient_user_id", "channel", name="uq_delivery"
        ),
        sa.UniqueConstraint(
            "provider_message_id", name=op.f("uq_notification_deliveries_provider_message_id")
        ),
    )
    op.create_index(
        "ix_delivery_claim", "notification_deliveries", ["status", "next_attempt_at"], unique=False
    )
    op.create_index(
        op.f("ix_notification_deliveries_ticket_id"),
        "notification_deliveries",
        ["ticket_id"],
        unique=False,
    )
    op.add_column(
        "users", sa.Column("max_identity_verified_at", sa.DateTime(timezone=True), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    op.execute("""
        DO $$ BEGIN
            IF EXISTS (SELECT 1 FROM notification_deliveries) OR
               EXISTS (SELECT 1 FROM users WHERE max_identity_verified_at IS NOT NULL) THEN
                RAISE EXCEPTION 'Delivery/identity history exists; restore a pre-delivery backup';
            END IF;
        END $$;
    """)
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "max_identity_verified_at")
    op.drop_index(
        op.f("ix_notification_deliveries_ticket_id"), table_name="notification_deliveries"
    )
    op.drop_index("ix_delivery_claim", table_name="notification_deliveries")
    op.drop_table("notification_deliveries")
    op.drop_table("max_destination_limits")
    # ### end Alembic commands ###
