"""company onboarding invitations house requests

Revision ID: e107a3cff433
Revises: 1c5baa831ec9
Create Date: 2026-09-19 23:05:29.469666
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "e107a3cff433"
down_revision: str | None = "1c5baa831ec9"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "company_onboarding_requests",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("legal_name", sa.String(length=300), nullable=False),
        sa.Column("short_name", sa.String(length=200), nullable=False),
        sa.Column("inn", sa.String(length=12), nullable=False),
        sa.Column("contact_name", sa.String(length=200), nullable=False),
        sa.Column("contact_email", sa.String(length=254), nullable=True),
        sa.Column("contact_phone", sa.String(length=40), nullable=True),
        sa.Column("comment", sa.String(length=2000), nullable=True),
        sa.Column("submitted_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("company_id", sa.Uuid(), nullable=True),
        sa.Column("status", sa.String(length=30), nullable=False),
        sa.Column("reviewed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("reviewed_by_user_id", sa.Uuid(), nullable=True),
        sa.Column("decision_reason", sa.String(length=2000), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "status IN ('submitted','under_review','needs_info','approved','rejected','cancelled')",
            name=op.f("ck_company_onboarding_requests_status"),
        ),
        sa.ForeignKeyConstraint(
            ["company_id"],
            ["management_companies.id"],
            name=op.f("fk_company_onboarding_requests_company_id_management_companies"),
        ),
        sa.ForeignKeyConstraint(
            ["reviewed_by_user_id"],
            ["users.id"],
            name=op.f("fk_company_onboarding_requests_reviewed_by_user_id_users"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_company_onboarding_requests")),
        sa.UniqueConstraint("company_id", name=op.f("uq_company_onboarding_requests_company_id")),
    )
    op.create_index(
        "uq_company_application_open_inn",
        "company_onboarding_requests",
        ["inn"],
        unique=True,
        postgresql_where=sa.text("status IN ('submitted','under_review','needs_info')"),
    )
    op.create_table(
        "employee_invitations",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("company_id", sa.Uuid(), nullable=False),
        sa.Column("invited_by_user_id", sa.Uuid(), nullable=True),
        sa.Column("organization_role", sa.String(length=30), nullable=False),
        sa.Column("token_hash", sa.String(length=64), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("status", sa.String(length=30), nullable=False),
        sa.Column("claimed_by_user_id", sa.Uuid(), nullable=True),
        sa.Column("claimed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("accepted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("revoked_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "organization_role IN ('operator','company_admin')",
            name=op.f("ck_employee_invitations_role"),
        ),
        sa.CheckConstraint(
            "status IN ('pending','claimed','accepted','expired','revoked')",
            name=op.f("ck_employee_invitations_status"),
        ),
        sa.ForeignKeyConstraint(
            ["claimed_by_user_id"],
            ["users.id"],
            name=op.f("fk_employee_invitations_claimed_by_user_id_users"),
        ),
        sa.ForeignKeyConstraint(
            ["company_id"],
            ["management_companies.id"],
            name=op.f("fk_employee_invitations_company_id_management_companies"),
        ),
        sa.ForeignKeyConstraint(
            ["invited_by_user_id"],
            ["users.id"],
            name=op.f("fk_employee_invitations_invited_by_user_id_users"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_employee_invitations")),
        sa.UniqueConstraint("token_hash", name=op.f("uq_employee_invitations_token_hash")),
    )
    op.create_index(
        op.f("ix_employee_invitations_company_id"),
        "employee_invitations",
        ["company_id"],
        unique=False,
    )
    op.create_table(
        "house_management_requests",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("company_id", sa.Uuid(), nullable=False),
        sa.Column("requested_address", sa.String(length=500), nullable=False),
        sa.Column("normalized_address", sa.String(length=500), nullable=False),
        sa.Column("requested_valid_from", sa.DateTime(timezone=True), nullable=False),
        sa.Column("basis_text", sa.String(length=2000), nullable=False),
        sa.Column("candidate_house_id", sa.Uuid(), nullable=True),
        sa.Column("submitted_by_user_id", sa.Uuid(), nullable=False),
        sa.Column("management_id", sa.Uuid(), nullable=True),
        sa.Column("status", sa.String(length=30), nullable=False),
        sa.Column("reviewed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("reviewed_by_user_id", sa.Uuid(), nullable=True),
        sa.Column("decision_reason", sa.String(length=2000), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "status IN ('submitted','under_review','needs_info','approved','rejected','cancelled')",
            name=op.f("ck_house_management_requests_status"),
        ),
        sa.ForeignKeyConstraint(
            ["candidate_house_id"],
            ["houses.id"],
            name=op.f("fk_house_management_requests_candidate_house_id_houses"),
        ),
        sa.ForeignKeyConstraint(
            ["company_id"],
            ["management_companies.id"],
            name=op.f("fk_house_management_requests_company_id_management_companies"),
        ),
        sa.ForeignKeyConstraint(
            ["management_id"],
            ["house_managements.id"],
            name=op.f("fk_house_management_requests_management_id_house_managements"),
        ),
        sa.ForeignKeyConstraint(
            ["reviewed_by_user_id"],
            ["users.id"],
            name=op.f("fk_house_management_requests_reviewed_by_user_id_users"),
        ),
        sa.ForeignKeyConstraint(
            ["submitted_by_user_id"],
            ["users.id"],
            name=op.f("fk_house_management_requests_submitted_by_user_id_users"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_house_management_requests")),
        sa.UniqueConstraint(
            "management_id", name=op.f("uq_house_management_requests_management_id")
        ),
    )
    op.create_index(
        op.f("ix_house_management_requests_company_id"),
        "house_management_requests",
        ["company_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_house_management_requests_normalized_address"),
        "house_management_requests",
        ["normalized_address"],
        unique=False,
    )
    op.add_column("auth_challenges", sa.Column("invitation_id", sa.Uuid(), nullable=True))
    op.create_foreign_key(
        op.f("fk_auth_challenges_invitation_id_employee_invitations"),
        "auth_challenges",
        "employee_invitations",
        ["invitation_id"],
        ["id"],
    )
    op.add_column(
        "management_companies", sa.Column("legal_name", sa.String(length=300), nullable=True)
    )
    op.add_column("management_companies", sa.Column("inn", sa.String(length=12), nullable=True))
    op.add_column(
        "management_companies", sa.Column("contact_name", sa.String(length=200), nullable=True)
    )
    op.add_column(
        "management_companies", sa.Column("contact_email", sa.String(length=254), nullable=True)
    )
    op.add_column(
        "management_companies", sa.Column("contact_phone", sa.String(length=40), nullable=True)
    )
    op.create_unique_constraint(
        op.f("uq_management_companies_inn"), "management_companies", ["inn"]
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    connection = op.get_bind()
    for table in (
        "company_onboarding_requests",
        "employee_invitations",
        "house_management_requests",
    ):
        if connection.execute(sa.text(f"SELECT EXISTS (SELECT 1 FROM {table})")).scalar():
            raise RuntimeError(
                "Administrative onboarding history retained; restore a pre-onboarding backup"
            )
    if connection.execute(
        sa.text(
            "SELECT EXISTS (SELECT 1 FROM management_companies WHERE inn IS NOT NULL "
            "OR legal_name IS NOT NULL OR contact_name IS NOT NULL "
            "OR contact_email IS NOT NULL OR contact_phone IS NOT NULL)"
        )
    ).scalar():
        raise RuntimeError(
            "Administrative company identity retained; restore a pre-onboarding backup"
        )
    if connection.execute(
        sa.text(
            "SELECT EXISTS (SELECT 1 FROM inbox_receipts WHERE event_type LIKE 'administration.%')"
        )
    ).scalar():
        raise RuntimeError("Administrative audit history retained; restore a pre-onboarding backup")
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f("uq_management_companies_inn"), "management_companies", type_="unique")
    op.drop_column("management_companies", "contact_phone")
    op.drop_column("management_companies", "contact_email")
    op.drop_column("management_companies", "contact_name")
    op.drop_column("management_companies", "inn")
    op.drop_column("management_companies", "legal_name")
    op.drop_constraint(
        op.f("fk_auth_challenges_invitation_id_employee_invitations"),
        "auth_challenges",
        type_="foreignkey",
    )
    op.drop_column("auth_challenges", "invitation_id")
    op.drop_index(
        op.f("ix_house_management_requests_normalized_address"),
        table_name="house_management_requests",
    )
    op.drop_index(
        op.f("ix_house_management_requests_company_id"), table_name="house_management_requests"
    )
    op.drop_table("house_management_requests")
    op.drop_index(op.f("ix_employee_invitations_company_id"), table_name="employee_invitations")
    op.drop_table("employee_invitations")
    op.drop_index(
        "uq_company_application_open_inn",
        table_name="company_onboarding_requests",
        postgresql_where=sa.text("status IN ('submitted','under_review','needs_info')"),
    )
    op.drop_table("company_onboarding_requests")
    # ### end Alembic commands ###
